# Generated by Django 5.0.4 on 2024-10-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentRate",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "student_code",
                    models.CharField(
                        help_text="Ingresa el código del estudiante", max_length=20
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ingresa el nombre del estudiante", max_length=200
                    ),
                ),
                ("year", models.IntegerField()),
                ("period", models.IntegerField()),
                ("course", models.CharField(max_length=200)),
                ("gender", models.CharField(max_length=20)),
                ("age", models.IntegerField()),
                ("grade", models.IntegerField()),
                ("family_size", models.CharField(max_length=200)),
                ("parent_status", models.CharField(max_length=200)),
                ("medu", models.CharField(max_length=200)),
                ("fedu", models.CharField(max_length=200)),
                ("travel_time", models.CharField(max_length=200)),
                ("study_time", models.CharField(max_length=200)),
                ("schoolsup", models.CharField(max_length=200)),
                ("activities", models.CharField(max_length=200)),
                ("higher", models.CharField(max_length=200)),
                ("internet", models.CharField(max_length=200)),
                ("famrel", models.CharField(max_length=200)),
                ("freetime", models.CharField(max_length=200)),
                ("health", models.CharField(max_length=200)),
                ("g1_conduct", models.IntegerField()),
                ("gf", models.IntegerField()),
                ("predicted_evaluation", models.CharField(max_length=100)),
                ("final_evaluation", models.CharField(max_length=100)),
                ("creation_date", models.DateField(auto_now=True)),
            ],
        ),
    ]
